# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(KERNEL_SRC)/../sm6475-modules/motorola/include
EXTRA_CFLAGS += -I$(KERNEL_SRC)/../sm6475-modules/motorola/include/linux/input/awinic
EXTRA_CFLAGS += -I$(KERNEL_SRC)/drivers/base

ifneq ($(filter m y,$(CONFIG_AW96XX_POWER_SUPPLY_ONLINE)),)
	EXTRA_CFLAGS += -DCONFIG_USE_POWER_SUPPLY_ONLINE
endif

KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../../../sensors/$(GKI_OBJ_MODULE_DIR)/Module.symvers

ifneq ($(filter m y,$(CONFIG_CAPSENSE_HALL_CAL)),)
    KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../../hall/$(GKI_OBJ_MODULE_DIR)/Module.symvers
    EXTRA_CFLAGS += -DCONFIG_CAPSENSE_HALL_CAL
endif

obj-m := awinic_sar.o
awinic_sar-objs := ./comm/aw_sar_comm_interface.o aw_sar.o ./aw963xx/aw963xx.o


