# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(KERNEL_SRC)/../sm6475-modules/motorola/drivers/power/pogo_pen_charger
EXTRA_CFLAGS += -I$(KERNEL_SRC)/../sm6475-modules/motorola/include

obj-m += pogo_pen_charger.o

KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../../misc/hall/$(GKI_OBJ_MODULE_DIR)/Module.symvers
